experiment_name: str()
save_directory: str(required=False)
sequence: list(include('seqobj'))
sequence_order: list(int())
channels: map(list(include('channelobj')),key=str())
exp_time: num(required=True) # in seconds
exp_start: timestamp(min='1970-01-01 01:00:00', max='2100-01-01 23:00:00', required=False)
exp_end: timestamp(min='1970-01-01 01:00:00', max='2100-01-01 23:00:00', required=False)
radar_files: str(required=False)
pulse_files: str(required=False)

---
seqobj:
  name: str()
  id_code: int()
  txrxname: list(str()) # List all of the radars active during the sequence
  txorrx: list(enum('rx','tx'))
  beamcodes: any(list(int()), list(list(int()))) #beamnumbers
  pulsecodes: any(list(int()), list(list(int()))) #pulsecodes
  pulsenums: any(list(int()), list(list(int())),required=False) #pulsenum

channelobj:
  name: str()
  sample_rate_numerator: int()
  sample_rate_denominator: int()
  is_complex: bool()
  numtype: str()
  num_subchannels: int(required=False)
  radardatatype: enum('txpulse','ionline','plasmaline')
  metadata: list(include('metadataobj'),required=False)
  uuid: str()
  declist: list(int(),required=False)

metadataobj:
  folder_name: str()
  type: str()
