experiment_name: str()
radartx: any(str(),list(str()))
radarrx: any(str(),list(str()))
save_directory: str(required=False)
sequence: list(include('seqobj'))
sequence_order: list(int())
sequence_repeats: list(int())
channels: map(list(include('channelobj')),key=str())
exp_time: num(required=True) # in seconds
exp_start: timestamp(min='1970-01-01 01:00:00', max='2100-01-01 23:00:00', required=False)
exp_end: timestamp(min='1970-01-01 01:00:00', max='2100-01-01 23:00:00', required=False)
radar_files: str(required=False)
pulse_files: str(required=False)

---
seqobj:
  name: str()
  id_code: int()
  txrxname: str()
  beamcodes: list(int()) #beamnumbers
  pulsecodes: list(int()) #pulsenumbers

channelobj:
  name: str()
  sample_rate_numerator: int()
  sample_rate_denominator: int()
  is_complex: bool()
  numtype: str()
  num_subchannels: int(required=False)
  radardatatype: enum('txpulse','ionline','plasmaline')
  uuid: str()
