code: 300
name: s480_8910
pulsetype: uncoded
baudlen: 30000
nbauds: 16
raster:
  blank:
    - 0
    - 700000
  calibration:
    - 7700000
    - 8300000
  clutter:
    - 700000
    - 800000
  full:
    - 0
    - 8910000
  noise:
    - 7100000
    - 7700000
  signal:
    - 800000
    - 7100000
  tx:
    - 0
    - 480000
  txnoise:
    - 7100000
    - 7700000
bauds:
  real:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
  imag:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
